-- ============================================================
-- Seed: 80+ Exercícios em Português
-- ============================================================

INSERT INTO exercises (name, muscle_group, secondary_muscles, equipment, instructions, difficulty, is_compound) VALUES

-- ==================== PEITO ====================
('Supino Reto com Barra', 'chest', ARRAY['shoulders', 'triceps'], 'barbell',
 'Deite no banco, segure a barra com pegada levemente mais larga que os ombros. Desça a barra até o peito e empurre de volta.',
 'intermediate', true),
('Supino Inclinado com Barra', 'chest', ARRAY['shoulders', 'triceps'], 'barbell',
 'Banco inclinado a 30-45°. Mesma técnica do supino reto, enfatiza a parte superior do peitoral.',
 'intermediate', true),
('Supino Declinado com Barra', 'chest', ARRAY['triceps'], 'barbell',
 'Banco declinado. Enfatiza a parte inferior do peitoral.',
 'intermediate', true),
('Supino com Halteres', 'chest', ARRAY['shoulders', 'triceps'], 'dumbbell',
 'Maior amplitude de movimento que com barra. Mantenha os cotovelos levemente flexionados.',
 'intermediate', true),
('Crucifixo com Halteres', 'chest', ARRAY['shoulders'], 'dumbbell',
 'Abra os braços com cotovelos levemente dobrados. Sinta o alongamento no peitoral.',
 'intermediate', false),
('Crossover no Cabo', 'chest', ARRAY['shoulders'], 'cable',
 'Puxe os cabos em arco até o centro do corpo. Excelente para contração do peitoral.',
 'beginner', false),
('Flexão de Braços', 'chest', ARRAY['shoulders', 'triceps', 'abs'], 'bodyweight',
 'Mãos levemente mais largas que os ombros. Mantenha o corpo reto. Desça até quase tocar o chão.',
 'beginner', true),
('Mergulho em Paralelas (Peito)', 'chest', ARRAY['triceps', 'shoulders'], 'bodyweight',
 'Incline o tronco ligeiramente para frente para enfatizar o peitoral.',
 'intermediate', true),

-- ==================== COSTAS ====================
('Levantamento Terra', 'back', ARRAY['glutes', 'legs', 'abs'], 'barbell',
 'Pés na largura dos quadris, barra sobre os pés. Mantenha as costas neutras, empurre o chão.',
 'advanced', true),
('Barra Fixa (Pull-up)', 'back', ARRAY['biceps', 'shoulders'], 'bodyweight',
 'Pegada pronada, puxe o corpo até o queixo ultrapassar a barra.',
 'intermediate', true),
('Remada Curvada com Barra', 'back', ARRAY['biceps', 'shoulders'], 'barbell',
 'Tronco inclinado ~45°. Puxe a barra em direção ao umbigo mantendo as costas retas.',
 'intermediate', true),
('Remada Unilateral com Halter', 'back', ARRAY['biceps'], 'dumbbell',
 'Apoie um joelho no banco. Puxe o halter em direção ao quadril.',
 'beginner', false),
('Puxada Frente (Lat Pulldown)', 'back', ARRAY['biceps'], 'cable',
 'Puxe a barra em direção ao peitoral superior mantendo o tronco levemente inclinado.',
 'beginner', true),
('Remada Baixa no Cabo', 'back', ARRAY['biceps'], 'cable',
 'Puxe o cabo em direção ao umbigo. Mantenha os cotovelos próximos ao corpo.',
 'beginner', false),
('Hiperextensão', 'back', ARRAY['glutes'], 'bodyweight',
 'No banco romano, eleve o tronco até ficar alinhado com as pernas.',
 'beginner', false),
('Chin-up (Pegada Supinada)', 'back', ARRAY['biceps'], 'bodyweight',
 'Pegada supinada. Foco maior nos bíceps comparado ao pull-up tradicional.',
 'intermediate', true),

-- ==================== OMBROS ====================
('Desenvolvimento com Barra', 'shoulders', ARRAY['triceps', 'abs'], 'barbell',
 'Pressione a barra do queixo para cima. Pode ser feito sentado ou em pé.',
 'intermediate', true),
('Desenvolvimento com Halteres', 'shoulders', ARRAY['triceps'], 'dumbbell',
 'Maior controle de cada braço independentemente. Pressione acima da cabeça.',
 'beginner', true),
('Elevação Lateral', 'shoulders', ARRAY[]::TEXT[], 'dumbbell',
 'Eleve os halteres lateralmente até a altura dos ombros. Cotovelos levemente dobrados.',
 'beginner', false),
('Elevação Frontal', 'shoulders', ARRAY[]::TEXT[], 'dumbbell',
 'Eleve os halteres à frente do corpo até a altura dos ombros.',
 'beginner', false),
('Encolhimento de Ombros', 'shoulders', ARRAY[]::TEXT[], 'barbell',
 'Eleve os ombros em direção às orelhas. Mantido por 1 segundo no topo.',
 'beginner', false),
('Face Pull', 'shoulders', ARRAY['back'], 'cable',
 'Puxe o cabo em direção ao rosto com as mãos separadas. Excelente para deltóide posterior.',
 'beginner', false),
('Arnold Press', 'shoulders', ARRAY['triceps'], 'dumbbell',
 'Começa com as palmas voltadas para você, rotaciona ao pressionar para cima.',
 'intermediate', true),

-- ==================== BÍCEPS ====================
('Rosca Direta com Barra', 'biceps', ARRAY[]::TEXT[], 'barbell',
 'Cotovelos fixos ao lado do corpo. Rosca até os bíceps contraírem completamente.',
 'beginner', false),
('Rosca Alternada com Halteres', 'biceps', ARRAY[]::TEXT[], 'dumbbell',
 'Alterne os braços. Pode incluir rotação do pulso ao subir (supinação).',
 'beginner', false),
('Rosca Concentrada', 'biceps', ARRAY[]::TEXT[], 'dumbbell',
 'Cotovelo apoiado na coxa. Isola completamente o bíceps.',
 'beginner', false),
('Rosca Martelo', 'biceps', ARRAY['forearms'], 'dumbbell',
 'Pegada neutra (polegar para cima). Trabalha braquial e antebraço.',
 'beginner', false),
('Rosca no Cabo', 'biceps', ARRAY[]::TEXT[], 'cable',
 'Tensão constante ao longo de todo o movimento.',
 'beginner', false),
('Rosca 21', 'biceps', ARRAY[]::TEXT[], 'barbell',
 '7 reps na metade inferior, 7 na metade superior, 7 completas.',
 'intermediate', false),

-- ==================== TRÍCEPS ====================
('Tríceps Testa', 'triceps', ARRAY[]::TEXT[], 'barbell',
 'Deite no banco. Dobre os cotovelos trazendo a barra à testa. Estenda.',
 'intermediate', false),
('Mergulho em Paralelas (Tríceps)', 'triceps', ARRAY['chest', 'shoulders'], 'bodyweight',
 'Tronco ereto para focar o tríceps. Desça até os cotovelos chegarem a 90°.',
 'intermediate', true),
('Extensão de Tríceps no Cabo', 'triceps', ARRAY[]::TEXT[], 'cable',
 'Puxe para baixo mantendo os cotovelos fixos ao lado do corpo.',
 'beginner', false),
('Tríceps Coice', 'triceps', ARRAY[]::TEXT[], 'dumbbell',
 'Tronco inclinado, cotovelo fixo. Estenda o braço para trás completamente.',
 'beginner', false),
('Francês com Halter', 'triceps', ARRAY[]::TEXT[], 'dumbbell',
 'Segure um halter com as duas mãos acima da cabeça. Dobre os cotovelos.',
 'beginner', false),
('Flexão Diamante', 'triceps', ARRAY['chest'], 'bodyweight',
 'Mãos formando um triângulo sob o peito. Foca os tríceps.',
 'intermediate', false),

-- ==================== PERNAS ====================
('Agachamento Livre com Barra', 'legs', ARRAY['glutes', 'abs', 'back'], 'barbell',
 'Barra nos trapézios. Agache até as coxas ficarem paralelas ao chão. Joelhos seguem os pés.',
 'advanced', true),
('Leg Press 45°', 'legs', ARRAY['glutes'], 'machine',
 'Pés na plataforma na largura dos ombros. Desça até 90° e empurre de volta.',
 'beginner', true),
('Extensão de Pernas', 'legs', ARRAY[]::TEXT[], 'machine',
 'Estenda as pernas completamente. Pausa no topo para máxima contração do quadríceps.',
 'beginner', false),
('Rosca Femoral', 'legs', ARRAY[]::TEXT[], 'machine',
 'Flexione os joelhos trazendo os tornozelos em direção aos glúteos.',
 'beginner', false),
('Stiff com Barra', 'legs', ARRAY['glutes', 'back'], 'barbell',
 'Joelhos levemente dobrados, desça a barra ao longo das pernas mantendo as costas retas.',
 'intermediate', true),
('Agachamento Búlgaro', 'legs', ARRAY['glutes'], 'dumbbell',
 'Pé traseiro apoiado no banco. Agache com a perna dianteira.',
 'intermediate', false),
('Avanço (Lunge)', 'legs', ARRAY['glutes'], 'dumbbell',
 'Dê um passo à frente e desça o joelho traseiro em direção ao chão.',
 'beginner', true),
('Agachamento Sumô', 'legs', ARRAY['glutes', 'abs'], 'barbell',
 'Pés mais abertos que os ombros, pontas dos pés para fora. Enfatiza adutores.',
 'intermediate', true),
('Hack Squat', 'legs', ARRAY['glutes'], 'machine',
 'Máquina inclinada. Foco no quadríceps. Pés posicionados baixo na plataforma.',
 'intermediate', true),
('Step-up com Halteres', 'legs', ARRAY['glutes'], 'dumbbell',
 'Suba em um banco ou plataforma alternando as pernas.',
 'beginner', true),

-- ==================== GLÚTEOS ====================
('Hip Thrust com Barra', 'glutes', ARRAY['legs'], 'barbell',
 'Ombros no banco, barra no quadril. Empurre o quadril para cima contraindo os glúteos.',
 'intermediate', false),
('Glute Bridge', 'glutes', ARRAY['legs'], 'bodyweight',
 'Deite de costas, joelhos dobrados. Eleve o quadril contraindo os glúteos.',
 'beginner', false),
('Cadeira Abdutora', 'glutes', ARRAY[]::TEXT[], 'machine',
 'Abra as pernas contra a resistência. Foco nos glúteos médio e mínimo.',
 'beginner', false),
('Kickback no Cabo', 'glutes', ARRAY[]::TEXT[], 'cable',
 'Em pé, puxe o cabo para trás com a perna estendida. Contrai o glúteo.',
 'beginner', false),
('Agachamento com Elástico', 'glutes', ARRAY['legs'], 'band',
 'Elástico acima dos joelhos. Agache mantendo os joelhos pressionando contra o elástico.',
 'beginner', true),

-- ==================== ABDÔMEN ====================
('Abdominal Infra', 'abs', ARRAY[]::TEXT[], 'bodyweight',
 'Elevação de pernas em 90°. Contraia o core para elevar os quadris levemente.',
 'beginner', false),
('Prancha', 'abs', ARRAY['shoulders', 'back'], 'bodyweight',
 'Posição de flexão com antebraços. Mantenha o corpo reto como uma prancha.',
 'beginner', false),
('Russian Twist', 'abs', ARRAY[]::TEXT[], 'bodyweight',
 'Sentado com pernas elevadas, gire o tronco de lado a lado.',
 'beginner', false),
('Abdominal com Roda (Ab Wheel)', 'abs', ARRAY['back', 'shoulders'], 'bodyweight',
 'Joelhos no chão, role a roda à frente estendendo o corpo, volte.',
 'advanced', false),
('Oblíquos no Cabo', 'abs', ARRAY[]::TEXT[], 'cable',
 'Puxe o cabo diagonalmente de cima para baixo. Trabalha os oblíquos.',
 'beginner', false),
('Crunch no Banco Declinado', 'abs', ARRAY[]::TEXT[], 'bodyweight',
 'Crunch com os pés presos no banco declinado para maior amplitude.',
 'beginner', false),
('Leg Raise na Barra', 'abs', ARRAY[]::TEXT[], 'bodyweight',
 'Pendurado na barra, eleve as pernas até 90°.',
 'intermediate', false),
('Mountain Climbers', 'abs', ARRAY['shoulders', 'legs'], 'bodyweight',
 'Posição de prancha, alterne os joelhos em direção ao peito rapidamente.',
 'beginner', false),

-- ==================== PANTURRILHAS ====================
('Gêmeos em Pé', 'legs', ARRAY[]::TEXT[], 'machine',
 'Eleve os calcanhares o máximo possível. Pausa no topo, desça completamente.',
 'beginner', false),
('Gêmeos Sentado', 'legs', ARRAY[]::TEXT[], 'machine',
 'Trabalha o sóleo (panturrilha profunda). Joelhos a 90°.',
 'beginner', false),
('Gêmeos no Leg Press', 'legs', ARRAY[]::TEXT[], 'machine',
 'Pontas dos pés na borda da plataforma. Estenda os tornozelos.',
 'beginner', false),

-- ==================== CARDIO ====================
('Corrida na Esteira', 'cardio', ARRAY['legs', 'abs'], 'machine',
 'Mantenha postura ereta, aterrisse com o meio do pé. Ajuste velocidade gradualmente.',
 'beginner', false),
('Bike Ergométrica', 'cardio', ARRAY['legs'], 'machine',
 'Ajuste o selim para que o joelho fique levemente dobrado no ponto mais baixo.',
 'beginner', false),
('Elíptico', 'cardio', ARRAY['legs', 'shoulders'], 'machine',
 'Movimento de baixo impacto. Excelente para recuperação ativa.',
 'beginner', false),
('Corda de Pular', 'cardio', ARRAY['legs', 'shoulders'], 'bodyweight',
 'Saltos pequenos, pés próximos ao chão. Ótimo para condicionamento.',
 'beginner', false),
('Burpee', 'cardio', ARRAY['chest', 'legs', 'abs'], 'bodyweight',
 'Agache, coloque as mãos no chão, role para flexão, volte e salte.',
 'intermediate', true),

-- ==================== FULL BODY ====================
('Power Clean', 'full_body', ARRAY['back', 'shoulders', 'legs'], 'barbell',
 'Levantamento olímpico. Puxe a barra do chão até os ombros em um movimento explosivo.',
 'advanced', true),
('Kettlebell Swing', 'full_body', ARRAY['glutes', 'back', 'shoulders'], 'kettlebell',
 'Impulsione o kettlebell com o quadril, não com os braços. Movimento balístico.',
 'intermediate', true),
('Thruster', 'full_body', ARRAY['legs', 'shoulders'], 'barbell',
 'Combine agachamento frontal com desenvolvimento. Movimento contínuo.',
 'advanced', true),
('TRX Row', 'back', ARRAY['biceps', 'abs'], 'bodyweight',
 'Incline o corpo, puxe as alças em direção ao peito mantendo o corpo reto.',
 'beginner', false),
('Farmer Walk', 'full_body', ARRAY['forearms', 'abs', 'back'], 'dumbbell',
 'Carregue halteres pesados e caminhe. Fortalece tudo, especialmente o core.',
 'beginner', true),
('Devil Press', 'full_body', ARRAY['chest', 'shoulders', 'legs'], 'dumbbell',
 'Burpee com halteres + press acima da cabeça. Condicionamento intenso.',
 'advanced', true),

-- ==================== ANTEBRAÇO ====================
('Rosca de Punho', 'back', ARRAY[]::TEXT[], 'barbell',
 'Antebraços apoiados nas coxas. Flexione o punho para cima e para baixo.',
 'beginner', false),
('Barra com Pegada Larga', 'back', ARRAY['biceps'], 'barbell',
 'Rosca direta com pegada mais larga que o normal. Trabalha braquiorradial.',
 'beginner', false),

-- ==================== MAIS EXERCÍCIOS ====================
('Supino Fechado', 'triceps', ARRAY['chest'], 'barbell',
 'Barra com pegada estreita (ombros largura). Foca os tríceps.',
 'intermediate', true),
('Peck Deck', 'chest', ARRAY[]::TEXT[], 'machine',
 'Cotovelos no suporte. Feche os braços à frente sentindo a contração.',
 'beginner', false),
('Pull-over com Halter', 'back', ARRAY['chest'], 'dumbbell',
 'Deitado, halter acima do peito. Desça atrás da cabeça em arco. Sinta o latíssimo.',
 'intermediate', false),
('Remada Cavalinho', 'back', ARRAY['shoulders'], 'barbell',
 'Puxe a barra verticalmente até a altura do peito com cotovelos acima.',
 'intermediate', false),
('Agachamento Hack com Barra', 'legs', ARRAY['glutes'], 'barbell',
 'Barra atrás das pernas, agache. Variação incomum que isola o quadríceps.',
 'intermediate', true),
('Cadeira Adutora', 'legs', ARRAY['glutes'], 'machine',
 'Feche as pernas contra a resistência. Trabalha adutores internos.',
 'beginner', false),
('Glute Kickback na Máquina', 'glutes', ARRAY[]::TEXT[], 'machine',
 'Em pé, empurre a plataforma para trás com o calcanhar. Extensão de quadril.',
 'beginner', false),
('Rosca Zottman', 'biceps', ARRAY['forearms'], 'dumbbell',
 'Suba com pegada supinada, rotacione para pronada ao descer. Trabalha todo o bíceps.',
 'intermediate', false);

-- ============================================================
-- Seed: Conquistas
-- ============================================================
INSERT INTO achievements (name, description, icon, category, requirement_type, requirement_value, xp_reward, rarity) VALUES
('Primeira Série', 'Complete seu primeiro set', '💪', 'milestone', 'total_sets', 1, 25, 'common'),
('Primeiro Treino', 'Complete seu primeiro treino', '🏋️', 'milestone', 'total_workouts', 1, 50, 'common'),
('Na Vibe', 'Treine 3 dias seguidos', '🔥', 'streak', 'streak', 3, 75, 'common'),
('Semana Completa', '7 dias de streak', '📆', 'streak', 'streak', 7, 150, 'rare'),
('Quinzena', '15 dias de streak', '⚡', 'streak', 'streak', 15, 300, 'rare'),
('Mês de Fogo', '30 dias de streak', '🔥', 'streak', 'streak', 30, 500, 'epic'),
('Trimestre Beast', '90 dias de streak', '💎', 'streak', 'streak', 90, 1000, 'epic'),
('Diamante', '365 dias de streak', '💎', 'streak', 'streak', 365, 5000, 'legendary'),
('Tonelada', 'Levante 1.000kg em um treino', '🏋️', 'volume', 'session_volume', 1000, 100, 'common'),
('5 Toneladas', '5.000kg em um treino', '💪', 'volume', 'session_volume', 5000, 200, 'rare'),
('Veterano', 'Complete 10 treinos', '⭐', 'milestone', 'total_workouts', 10, 100, 'common'),
('Dedicado', 'Complete 25 treinos', '🌟', 'milestone', 'total_workouts', 25, 200, 'rare'),
('Consistente', 'Complete 50 treinos', '🏆', 'milestone', 'total_workouts', 50, 400, 'epic'),
('Centurião', 'Complete 100 treinos', '💯', 'milestone', 'total_workouts', 100, 800, 'epic'),
('Lenda', 'Complete 365 treinos', '👑', 'milestone', 'total_workouts', 365, 5000, 'legendary'),
('PR Machine', 'Bata 10 recordes pessoais', '📈', 'strength', 'total_prs', 10, 300, 'rare'),
('Super Forte', 'Bata 25 recordes pessoais', '💪', 'strength', 'total_prs', 25, 600, 'epic'),
('Madrugador', 'Treine antes das 6h', '🌅', 'consistency', 'early_workout', 1, 100, 'rare'),
('Coruja', 'Treine depois das 22h', '🦉', 'consistency', 'late_workout', 1, 100, 'rare'),
('Volume Absurdo', 'Levante 100.000kg no total', '🚀', 'volume', 'total_volume', 100000, 1000, 'legendary');
